### ISSUE TITLE
Redaction annotations created in PDFTron are black-boxed in other viewers

### ISSUE THREAD

**Issue by creage** [PDFTron/webviewer-react-sample#11]
I'm not sure if it is the right repo to report this issue to, but since it is the one of the most popular here, I hope to get proper attention to it. Feel free to move it to the right repo if needed.

I'm having issues with redaction annotations created in PDFTron. Such file look fine in PDFTRon WebViewer - redactions are marked in purple boxes, I can still read the redacted content, and hovering over the redaction will show me how the final result will look.

But when I open that file in other viewers (Adobe Acrobat, PDFJS), the redaction annotations are marked as already applied. I cannot see the content, the areas are marked in black.

If I make redaction annotations in Adobe Acrobat - they look fine both in PDFTron, and in Adobe Acrobat - purple boxes, visible content, black on hover.

Take a look at the example PDF: [Gartner Reprint.pdf](https://github.com/PDFTron/webviewer-react-sample/files/6305041/Gartner.Reprint.pdf)

There are three redactions created on the first page. **First two** redactions created in **PDFTron**, the **last one** created in **Adobe Acrobat**.

### All three redactions look fine in PDFTron:
![image](https://user-images.githubusercontent.com/910967/114583949-6a6ad580-9c82-11eb-8db6-680231d8d08f.png)
😕 
### The first two look broken in Adobe Acrobat, and in PDFJS:
![image](https://user-images.githubusercontent.com/910967/114584033-840c1d00-9c82-11eb-9380-a5ee836ff5f6.png)

😞 

Apparently, redactions created in PDFtron do not comply with standards.

**Comment by mparizeau-pdftron** [comment]
Thanks for the detailed description! Since this isn't directly related to our react sample could you please repost it in our community forum and that will ensure that someone will get back to you shortly https://community.pdftron.com/
