### ISSUE TITLE
Cant download the pdf in React app after making freeText Annontation

### ISSUE THREAD

**Issue by indro10** [PDFTron/webviewer-react-sample#12]
I am not able to download the pdf using the webviewer React app or even send the blob of the pdf to the server  after i make a  free-Text annotation programmatically.
adding this code on the app ..after documentLoaded.. prevents the download and gives the following error 
---->TypeError: Cannot convert undefined or null to object  .......CoreControls.js:938<------

Code for free text annotaion

const freeText = new Annotations.FreeTextAnnotation();
        freeText.PageNumber = 1;
        freeText.X = 150;
        freeText.Y = 200;
        freeText.Width = 150;
        freeText.Height = 50;
        freeText.setPadding(new Annotations.Rect(0, 0, 0, 0));
        freeText.setContents('My Text');
        freeText.FillColor = new Annotations.Color(0, 255, 255);
        freeText.FontSize = '16pt';
  
        annotManager.addAnnotation(freeText, { autoFocus: false });
        annotManager.redrawAnnotation(freeText);

![image](https://user-images.githubusercontent.com/46354600/114934787-000b8e00-9e58-11eb-98a3-fe14339454ac.png)

**Comment by mparizeau-pdftron** [comment]
It looks like we've recently fixed this issue and it's a part of our stable nightly build. See here for how to update to our stable nightly build https://www.pdftron.com/documentation/web/faq/webviewer-nightly-build/
