### ISSUE TITLE
About multiple language support for editing pdf text.

### ISSUE THREAD

**Issue by dsardar099** [PDFTron/webviewer-react-sample#16]
Hello PdfTron!
Is it possible to edit pdf text in some Indian language like **Bengali, Hindi or Gujrati** from any other language?
![image](https://user-images.githubusercontent.com/76544800/144802594-5a7a4ba1-f876-472a-b685-948d449557ab.png)

![image](https://user-images.githubusercontent.com/76544800/144802808-01fe2d3c-31db-4b89-9361-3d14e304567f.png)

**TO**

![image](https://user-images.githubusercontent.com/76544800/144802961-20e0fbc3-33a1-4cdd-8f15-f3120c5ca9c2.png)

**Currently it is not showing that new text in Indian language. It is showing blank space.**
![image](https://user-images.githubusercontent.com/76544800/144803120-dcf00395-1bc4-42f7-a276-eace1ea37fb7.png)

**Comment by mparizeau-pdftron** [comment]
Since this issue isn't specific to the react sample can you fill out this form to have it handled by our support team https://www.pdftron.com/form/request/

Thanks!
