### ISSUE TITLE
Getting window is not defined

### ISSUE THREAD

**Issue by beatrizpatriota** [PDFTron/webviewer-react-sample#23]
![image](https://github.com/PDFTron/webviewer-react-sample/assets/26945574/6f1e9799-42d5-4104-b51c-c5537c96b5b8)

**Comment by mparizeau-pdftron** [comment]
I wasn't able to reproduce this issue when running the sample. From the error it looks like you're trying to use pdfjs-express, so you could submit a question on the community forum here https://pdfjs.community/
