### ISSUE TITLE
Is it possible to disable text selection and text copy from file in WebViewer?

### ISSUE THREAD

**Issue by twravindra** [PDFTron/webviewer-react-sample#25]
I am working on requirement where I need to disable text selection and text copy from WebViewer.

I tried using `isReadOnly: true,` flag in WebViewer like below:

`WebViewer(
                {
                    preloadWorker: 'PDF',
                    path: 'lib',
                    licenseKey:
                        license,
                    initialDoc: file,
                    isReadOnly: true,
                    extension: 'pdf',
                    enableOptimizedWorkers: true,
                    disableObjectURLBlobs: true,
                    useDownloader: false,
                    fullAPI: true,
                    disabledElements: [
                        'viewControlsButton',
                        'viewControlsOverlay',
                        'contextMenuPopup',
                        'textPopup',
                    ],
                },
                viewer.current as HTMLDivElement,
            )`
            
Is it possible to disable text selection and text copy from WebViewer?

**Comment by mparizeau-pdftron** [comment]
Yep, you can all the following
```
instance.UI.disableFeatures([instance.UI.Feature.TextSelection]);
```

See here for more features you can disable https://docs.apryse.com/api/web/UI.html#.Feature__anchor

**Comment by twravindra** [comment]
Thanks. This worked.
