### ISSUE TITLE
Webviewer is not loading when distribution X-Frame-Options set to DENY 

### ISSUE THREAD

**Issue by sadashiv-sumasoft** [PDFTron/webviewer-react-sample#32]
Hi, 

I am using the PDFTron webviewer to show the document as well as the PPTX in my React applications.
Our application is hosted on AWS and delivered through CloudFront.
We have the cloudfront response headers policy enabled for security reasons, and that policy has X-Frame-Options set to DENY, which we cannot set to "SAMEORIGIN". and that X-Frame-Options stopping our webviewer from getting loads.

Could you please suggest some solutions for the above problem?
Thank you in advance.

![WebViewerNotLoading](https://github.com/PDFTron/webviewer-react-sample/assets/89510166/b478bd8f-c06a-4abc-a7aa-9283f293af5e)

**Comment by sadashiv-sumasoft** [comment]
Yes, I can see that the recent release has a WebComponent feature.
I implemented that in my code, and it works for me.

I feel there are issues while unmounting that web component. When we go to the previous page from the web component page, our whole website is getting re-loaded.

```
  WebViewer.WebComponent(
      {
        path: "/webviewer/lib",
        fullAPI: true, //This is added to create the flattened pdf
        initialDoc: fileInfo.cdnUrl,
      },
      viewer.current
    ).then((instance) => {
    //my own custom logic
    })
      
   ```

**Comment by mparizeau-pdftron** [comment]
Since this sounds a bit more complicated and may not be related to the react sample can you please submit a ticket here https://support.apryse.com/support/tickets/new

**Comment by sadashiv-sumasoft** [comment]
Thanks for your advice, @mparizeau-pdftron! I will create one support ticket for the above issue.
