### ISSUE TITLE
Feature Request: WebViewer - Instance Creator - Iframe on Sharepoint

### ISSUE THREAD

**Issue by Belisarith** [PDFTron/webviewer-react-sample#5]
The usecase is an React app, which is served on sharepoint. On sharepoint "html" endings are not served by the browser. In consequence when using the WebViewer library, the browser downloads the index.html file located in the webviewer/lib directory, instead of showing it. This issue can be remidied by using an **index.aspx** instead of **index.html**.

However the way the WebViewer function, which creates the instance in the iframe works, there is no way to specify the type of the index file. I can for my test, circumvent the problem by manually replacing the index.html with index.aspx in the webviewer.min.js file. The webviewer can then be used inside an react application hosted on sharepoint.

I suggest you add the following option to the WebViewer instance creator function options object: "**indexFileType**"

So that you can use the function like this:
```
WebViewer(
          {
            path: "somepath",
            initialDoc: "somefile",
            indexFileType: "aspx"
          },
)
```

Depending on this option the iframe "src" attribute is either using "index.html" by default or index.**indexType.**

**FYI**: I am not sure, if this is the correct repo for this issue. However, since I am evaluating on using WebViewer inside an React app, I found no better repo. Feel free, to point me in the right direction and I will repost the Feature request there.

**Comment by mparizeau-pdftron** [comment]
Thanks for the question! There's an option in the WebViewer constructor (though it looks like it's undocumented right now) that lets you specify the exact path you want for the src of the iframe (relative to the path option).

By default the **html5Path** option is set to `./ui/index.html` so you could try passing `html5Path: './ui/index.aspx'`
Does it work if you do that?

We've actually been doing a little testing lately and had similar issues with the html/aspx stuff. If you're able to get it working with the aspx file we'd be interested in seeing your code/setup and how it worked. If you have time you could post it here or email me directly at mparizeau@pdftron.com, thanks!

**Comment by Belisarith** [comment]
Thank you for the hint. _Please note:_ The html5Path is missing in the type.d.ts file.
I added the following option: ` html5Path: "ui/index.aspx",` and it is working. `html5Path: ".ui/index.aspx` does not work.

**One issue remains**: Sharepoint (at least our sharepoints) do not allow json files in SiteAssets. All the webviewer files are located in SiteAssets (see description below). Therefore, the labeling which to my understanding refers to the translation-json-files does not work, because I am not able to copy the files located in the ui/i18n folder. Is there an option to explicitly set the location of the translation file? I could then rename the file to something like .txt and think to get it working. 

My set-up for sharepoint is the following:
I copied the webviewer folder to sharepointUrl/SiteAssets. Inside the folder i renamed the index.html to index.aspx.
My main react app index.aspx file is located inside SitePages and the transpiled react javascript files and other assets are also located in sharepointUrl/SiteAssets. This set-up works for me, you can also serve the react app in fullscreen page mode with this (no sharepoint top bar or anything else).

Please let me know, if you would like to know anything else regarding the set-up with sharepoint. I'm happy to help.

**Comment by mparizeau-pdftron** [comment]
I haven't actually tried this, but does this help? https://sharepoint.stackexchange.com/a/169466

> In Central Administration, navigate to Manage Web Applications. Highlight the Web Application you're uploading to, then click on Blocked File Types in the ribbon. Find the file type, in this case json, and remove it, then click OK. That should allow you to upload json files, unless there are restrictions imposed elsewhere (e.g. IIS Request Filtering).

**Comment by Belisarith** [comment]
Thank you for pointing this out. However, this is not an option for this case.
Again like with the html5Path it would help to allow specifying the docFormat explictly as an option in the WebViewer constructor.
For now, it works for me, when I change the backend loadpath in webviewer-ui.min.js file from `{backend:{loadPath:"./i18n/{{ns}}-{{lng}}.json"}}` to `{backend:{loadPath:"./i18n/{{ns}}-{{lng}}.trans"}}`. I subsequently renamed all files in the i18n folder to .trans instead of json and it works on Sharepoint.

I guess when I have time, I can make a pull request in the webviewer-ui repository for this option.

I guess we can close this issue as there is nothing which can be done adhoc and it is the wrong repo.

**Comment by mparizeau-pdftron** [comment]
Making the change from the UI like you did would be the way to do it right now. If you'd like to make a pull request we'd be happy to take a look! I'll close this ticket then.
