### ISSUE TITLE
Cannot find how to save cropped area in reactjs PDFTron

### ISSUE THREAD

**Issue by saisk73** [PDFTron/webviewer-react-sample#9]
I cannot find function in the documentation to save the selected are in PDFTron. I want to get the cropped area and make an API call. Can anyone help me with getting cropped are in the pdf?

**Comment by mparizeau-pdftron** [comment]
Since this isn't directly related to the WebViewer React sample I would recommend that you fill out the form here and someone will be able to answer your question. https://www.pdftron.com/form/request/
